//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cede_Dotnet_WebApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoEstudiante
    {
        public int IdCurso { get; set; }
        public int CedulaEstudiante { get; set; }
        public bool Cancelada { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
